version: "3.9"

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  web:
    build: .
    entrypoint: ./entrypoint-dev.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy


  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

  # celery:
  #   build: .
  #   command: celery -A django_base worker --loglevel=info
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis